export const DataMap = {
  originalThreshold : {
    roll_ATTITUDE: 0.519040579,
    pitch_ATTITUDE: 0.330952408,
    yaw_ATTITUDE: 4.426681577,
    xacc_RAW_IMU: 505.059753,
    yacc_RAW_IMU: 253.607117,
    zacc_RAW_IMU: 592.7912866,
    xgyro_RAW_IMU: 2419.060251, 
    ygyro_RAW_IMU: 1655.598837,
    zgyro_RAW_IMU: 1430.775122,
    xmag_RAW_IMU: 432.8393278,
    ymag_RAW_IMU: 365.9837014,
    zmag_RAW_IMU: 566.2303151,
    vibration_x_VIBRATION: 4.997481432,
    vibration_y_VIBRATION: 3.934628874,
    vibration_z_VIBRATION: 9.405666076,
  },
  dependent_var: [
    'roll_ATTITUDE',
    'pitch_ATTITUDE',
    'yaw_ATTITUDE',
    'xacc_RAW_IMU',
    'yacc_RAW_IMU',
    'zacc_RAW_IMU',
    'xgyro_RAW_IMU',
    'ygyro_RAW_IMU',
    'zgyro_RAW_IMU',
    'xmag_RAW_IMU',
    'zmag_RAW_IMU',
    'ymag_RAW_IMU',
    'vibration_x_VIBRATION',
    'vibration_y_VIBRATION',
    'vibration_z_VIBRATION',
  ],
  independent_var: [
    'roll_ATTITUDE',
    'pitch_ATTITUDE',
    'yaw_ATTITUDE',
    'xacc_RAW_IMU',
    'yacc_RAW_IMU',
    'zacc_RAW_IMU',
    'xgyro_RAW_IMU',
    'ygyro_RAW_IMU',
    'zgyro_RAW_IMU',
    'xmag_RAW_IMU',
    'ymag_RAW_IMU',
    'zmag_RAW_IMU',
    'vibration_x_VIBRATION',
    'vibration_y_VIBRATION',
    'vibration_z_VIBRATION',
    'accel_cal_x_SENSOR_OFFSETS',
    'accel_cal_y_SENSOR_OFFSETS',
    'accel_cal_z_SENSOR_OFFSETS',
    'chan12_raw_RC_CHANNELS',
    'chan13_raw_RC_CHANNELS',
    'chan14_raw_RC_CHANNELS',
    'chan15_raw_RC_CHANNELS',
    'chan16_raw_RC_CHANNELS',
    'mag_ofs_x_SENSOR_OFFSETS',
    'mag_ofs_y_SENSOR_OFFSETS',
    'vx_GLOBAL_POSITION_INT',
    'vy_GLOBAL_POSITION_INT',
    'x_LOCAL_POSITION_NED',
    'vx_LOCAL_POSITION_NED',
    'vy_LOCAL_POSITION_NED',
    'nav_pitch_NAV_CONTROLLER_OUTPUT',
    'nav_bearing_NAV_CONTROLLER_OUTPUT',
    'servo3_raw_SERVO_OUTPUT_RAW',
    'servo8_raw_SERVO_OUTPUT_RAW',
    'groundspeed_VFR_HUD',
    'airspeed_VFR_HUD',
    'chancount_RC_CHANNELS',
    'press_abs_SCALED_PRESSURE',
    'Vservo_POWER_STATUS',
    'voltages1_BATTERY_STATUS',
  ],
  table_header: [
    'DRONE ID',
    'TIME',
    'ROLL',
    'PITCH',
    'YAW',
    '가속도 X',
    '가속도 Y',
    '가속도 Z',
    '각속도 X',
    '각속도 Y',
    '각속도 Z',
    '지자기 X',
    '지자기 Y',
    '지자기 Z',
    '진동값 X',
    '진동값 Y',
    '진동값 Z',
    '가속도 X ofs',
    '가속도 Y ofs',
    '가속도 Z ofs',
    '지자기 X ofs',
    '지자기 Y ofs',
    '지표면 vX',
    '지표면 vY',
    '로컬 X',
    '로컬 vX',
    '로컬 vY',
    '목표 Pitch',
    '목표 Bearing',
    '서보모터 3',
    '서보모터 8',
    '지표면 속도',
    '대기 속',
    '기압계',
    '전원 공급 장치',
    '베터리',
    '입력 채널 수',
    '채널 12',
    '채널 13',
    '채널 14',
    '채널 15',
    '채널 16',
  ],
  mini_header: [
    '예측값',
    '실제값',
    'DRONE ID',
    'TIME',
    'Roll',
    'Pitch',
    'Yaw',
    '가속도 X',
    '가속도 Y',
    '가속도 Z',
    '각속도 X',
    '각속도 Y',
    '각속도 Z',
    '지자기 X',
    '지자기 Y',
    '지자기 Z',
    '진동값 X',
    '진동값 Y',
    '진동값 Z',
    '가속도 Xcol',
    '가속도 Ycol',
    '가속도 Zcol',
    '지자기 Xoff',
    '지자기 Yoff',
    '지표면 vX',
    '지표면 vY',
    '로컬 X',
    '로컬 vX',
    '로컬 vY',
    '목표 Pitch',
    '목표 Bearing',
    '서보모터 3',
    '서보모터 8',
    '지표면 속도',
    '대기 속',
    '기압계',
    '전원 공급 장치',
    '베터리',
    '입력 채널 수',
    '채널 12',
    '채널 13',
    '채널 14',
    '채널 15',
    '채널 16',
  ],
  monitorMap: {
    droneId: 'None',
    totalDistance: 'None',
    elapsedDistance: 'None',
    remainDistance: 'None',
    startTime: 'None',
    completeTime: 'None',
    droneRawState: {
      WP_NO: 'None',
      POWER_V: 'None',
      TEMPERATURE_C: 'None',
      GPS_STATE: 'None',
      HDOP: 'None',
      DR_LAT: 'None',
      DR_LON: 'None',
      DR_ALT: 'None',
      DR_SPEED: 'None',
    },
  } //as MonitorMap
}

