image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  IMAGE: $CI_REGISTRY/tips/tips-client-web-app:${CI_COMMIT_BRANCH}-latest

stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE 
      --build-arg API_GATEWAY_IP=$API_GATEWAY_IP
      --build-arg API_GATEWAY_PORT=$API_GATEWAY_PORT
      --build-arg API_GATEWAY_PATH=$API_GATEWAY_PATH
      --build-arg AI_STREAM_SERVICE_PORT=$AI_STREAM_SERVICE_PORT
      --build-arg GCS_PORT=$GCS_PORT
      --build-arg GAION_IP=$GAION_IP
      -f tft.Dockerfile
      .
    - docker push $IMAGE
  only:
    refs:
      - main
      - cicd


deploy:
  image: ubuntu:latest
  stage: deploy
  only:
    - main
    - cicd
  before_script:
    - apt-get -yq update
    - apt-get -yqq install ssh
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && docker compose pull && docker compose up -d && exit"
  after_script:
    - rm -rf ~/.ssh